# Generated by Django 2.2.5 on 2021-04-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('sub', models.CharField(max_length=255)),
                ('marks', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
    ]
